name = "TensorDepot"
uuid = "a265fce4-34b0-4e6b-9b08-892587f3fa1f"
authors = ["Willow Ahrens"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
